config/routes.rb
Rails.application.routes.draw do
  
	get 'signup', to: 'users#new'
	resources :users, except: [:new]
	root 'welcome#home'
  resources :beers

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
	belongs_to :user
	has_many :beer_categories
	has_many :categories, through: :beer_categories
	validates :user_id, presence: true
end

app/models/beer_category.rb
class BeerCategory < ActiveRecord::Base
  belongs_to :beer
  belongs_to :category
end

app/models/best_beer.rb
class BestBeer < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :beer_categories
  has_many :beers, through: :beer_categories
end

app/models/user.rb
class User < ApplicationRecord
	has_many :beers
	before_save {self.email = email.downcase}
	has_many :comments, dependent: :destroy 
	validates :username, presence: true, 
	uniqueness: {case_sensitive:false},
	length: {minimum: 3, maximum: 25 }
	VALIDE_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length:{maximum: 105},
	uniqueness: {case_sensitive:false},
	format: {with: VALIDE_EMAIL_REGEX}
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	if !logged_in?
  		flash[:danger] = "You must be logged in to perform that action"
  		redirect_to root_path
  	end
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.paginate(page: params[:page], per_page: 5)
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new

  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)
    @beer.user = current_user
    
    respond_to do |format|
      if @beer.save
        flash[:success] = "Beer was successfully added"
        format.html { redirect_to @beer }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        flash[:success] = "Beer was successfully updated"
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    flash[:danger] = "Beer was successfully destroyed"
    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :beer_type, :country, :price, category_ids: [])
    end

    def require_same_user
      if current_user != @beer.user
        flash[:danger] = "You can only edit or delete your own beer"
        redirect_to beers_path
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only:[:show, :edit]
  def index
  	@categories = Category.paginate(page: params[:page],per_page: 5)
  end

  def new
  	@category = Category.new
  end

  def create
  	@category = Category.new(category_params)
  	if @category.save
  		flash[:success] = "Category was created successfully"
  		redirect_to categories_path
  	else
  		render 'new'
  	end

    def show
      @category = Category.find(params[:id])
      @category_articles = @category.beers.paginate(page: params[:page],per_page: 5)
    end


  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
      @categories = Category.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
		   session[:user_id] = user.id
		   flash[:succes] = "You have successfully logged in"
		   redirect_to user_path(user)
		else
			flash.now[:danger] = "There was something wrong with Your login info"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end
  def create
    @ip = request.remote_ip
    debugger
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:succes] = "Welcome to BeerBlog #{@user.username}"
      redirect_to user_path(@user)  
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      flash[:succes] = "Your accoutn was update succesfuly"
      redirect_to beers_path
    else
      render 'edit'
    end
  end


  def show
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end
  def set_user
    @user = User.find(params[:id])
  end

   def require_same_user
      if current_user != @user
        flash[:danger] = "You can only edit or delete your own account"
        redirect_to users_path
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_for(user, options = {size: 20})
		require 'open-uri'
		require 'nokogiri'
		#debugger
		if user.avatar
			#debugger
			image_tag(user.avatar, alt: user.username, class: "img-circle")
		else
			page = Nokogiri::HTML(open("https://www.avatarapi.com/js.aspx?email=#{user.email}&size=128"))
			#debugger
			user.avatar = unless page.css("img").empty?
			page.css("img").attr("src").value
		else
			"https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Beer_mug.svg/1024px-Beer_mug.svg.png"
		end
			user.save
			image_tag(user.avatar, alt: user.username, class: "img-circle", size: 20, id: "avatar")
		end
	end
end

app/helpers/beer_type_helper.rb
module BeerTypeHelper
end

app/helpers/beers_helper.rb
module BeersHelper
	
end

app/helpers/best_beers_helper.rb
module BestBeersHelper
end

app/helpers/users_helper.rb
module UsersHelper
	include HTTParty
		def localization(ip)
			base_uri = 'https://freegeoip.net/json/'
			path = ip.to_s
			loc = HTTParty.get(base_uri+path)
		end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/beers/_beer.html.erb
<% obj.each do |beer| %>
<div class="row">
  <div class="col-xs-4 col-xs-offset-4 ">
    <div class="well well-lg">
      <div class="beer-name">
        <%= link_to beer.name, beer_path(beer) %>
      </div>
      <div class="beer-type">
      <%= beer.beer_type %> 
      </div>
      <div class="beer-country">
        <%= beer.country %>
      </div>
      <div class="beer-price">
      <%= simple_format(number_to_currency(beer.price, locale: :pl,strip_insignificant_zeros: false)) %>
      </div>

<div class="article-meta-details">
  <small>Created by: <%= beer.user.username if beer.user %>, <%= time_ago_in_words(beer.created_at) %> ago,
    last updated: <%= time_ago_in_words(beer.updated_at) %> ago </small>



</div>
      <% if beer.categories.any? %>
        <p>Categories: <%= render beer.categories %></p>
      <% end %>

      <% if logged_in? && current_user == beer.user %>
        <div class="article-actions">
          <%= link_to 'Edit this beer', edit_beer_path(beer), class: "btn btn-xs btn-primary" %> 
          <%= link_to "Delete this beer", beer_path(beer), method: :delete,
          data: {confirm: "Are You sure?"}, 
          class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/beers/_form.html.erb
 <div class="row"> 
   <div class="col-xs-6">
    <%= form_with(model: beer, local: true, class: "form-horizontal", role: "form") do |form| %>
    <% if beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
        <% beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= form.label :name %>
      </div>
      <div class="col-sm-8">
        <%= form.text_field :name, id: :beer_name,class: "form-control", placeholder: "Beer name", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= form.label :country %>
      </div>
      <div class="col-sm-8">
        <%= form.text_field :country, id: :beer_country, class: "form-control", placeholder: "Country where beer was made" %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= form.label :price %>
      </div>
      <div class="col-sm-8">
        <%= form.text_field :price, id: :beer_price, class: "form-control", placeholder:"The price of Your beer" %>
      </div>
    </div>
<div class="form-group">
      <div class="row">
        <div class="col-sm-offset-2 col-sm-10">
          <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do|cb| %>
            <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    <% end %>
    <div class="col-xs-6 col-xs-offset-4">
    [ <%= link_to 'Cancel request and return to beers listing', beers_path %> ]
    </div>
  </div>
</div>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form', beer: @beer %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1 align="center">Beers</h1>
<div align="center">
<%= will_paginate %>
</div>
<%= render 'beer', obj: @beers %>
<div align="center">
<%= will_paginate %>
</div>

app/views/beers/new.html.erb
<h1 id="title">Add Beer by Your own!</h1>

<%= render 'form', beer: @beer %>

app/views/beers/show.html.erb
<h2 align="center">Name: <%= @beer.name %></h2>
<div class="well col-xs-8 col-xs-offset-2">
	<h4 class="center type"><strong>Type:</strong></h4>
	<hr><%= simple_format(@beer.beer_type)%>

	<h4 class="center"><strong>Country:</strong></h4>
	<hr><%= simple_format(@beer.country)%>

	<h4 class="center"><strong>Price:</strong></h4>
	<hr><%= simple_format(number_to_currency(@beer.price, locale: :pl,strip_insignificant_zeros: false))%>
	<% if @beer.categories.any? %>
	 <p>Categories: <%= render @beer.categories %></p>
	<% end %>

	<div class="article-actions">
		<%= link_to 'Edit this beer', edit_beer_path(@beer), class: "btn btn-xs btn-primary" %> 
		<%= link_to 'View all beers', beers_path, class: "btn btn-xs btn-success" %>
		<%= link_to "Delete this beer", beer_path(@beer), method: :delete,
		data: {confirm: "Are You sure?"}, 
		class: "btn btn-xs btn-danger" %>
	</div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> &nbsp; </span>

app/views/categories/_form.html.erb
 <div class="row"> 
   <div class="col-xs-6">
    <%= form_with(model: category, local: true, class: "form-horizontal", role: "form") do |form| %>
    <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= form.label :name %>
      </div>
      <div class="col-sm-8">
        <%= form.text_field :name, id: :category_name,class: "form-control", placeholder: "category name", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    <% end %>
    <div class="col-xs-6 col-xs-offset-4">
    [ <%= link_to 'Cancel request and return to categories listing', categories_path %> ]
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1 align="center">Categories</h1>
<div align="center">
  <%= will_paginate %>
</div>
  <% @categories.each do |category| %>
    <ul class = "listing">
      <div class="row">
		  <div class="well col-md-4 col-md-offset-4">
	      	<li class="article-title">
      		<%= link_to "#{category.name}",category_path(category) %>
	      	</li>
	      	<li><small><%= pluralize(category.beers.count, "beers") %> </small></li>
	      </div>
	    </div>
    </ul>
  <% end %>
  <div align="center">
  <%= will_paginate %>
 </div>

app/views/categories/new.html.erb
<h1 id="title">Add Category by Your own!</h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category : " + @category.name %></h1>
<div align="center">
</div>
<%= render 'beers/beer', obj: @category.beers %>
<div align="center">
</div>

app/views/layouts/_messages.html.erb
<div class = "row">
  <div class="col-xs-10 col-xs-offset-1">
	<% flash.each do |name,msg| %>
		<div class ='alert alert-<%="#{name}" %>'>
		  <a href="#" class ="close" data-dismiss="alert">	&#215;</a>
		  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
	    </div>
  <% end %> 
 </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to image_tag("https://static.skillshare.com/uploads/project/e053807898f6a9de77d2a0b56ae20050/b3e2f72e", id: "logo",alt: "Beer"), root_path %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Beers", beers_path, class: "active" %> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Beer", new_beer_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Categories", categories_path %></li>
            <% Category.all.each do |category| %>
            <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Your Profile", edit_user_path(current_user) %></li>
              <li><%= link_to "Show Your Profile", user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>

          <%else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeerBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
  	<%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="row"> 
   <div class="col-xs-8">
    <%= form_with(model: @user, local: true, class: "form-horizontal", role: "form") do |form| %>
    
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= form.label :username %>
      </div>
      <div class="col-sm-8">
        <%= form.text_field :username, id: :user_name, class: "form-control", placeholder: "user name", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= form.label :email %>
      </div>
      <div class="col-sm-8">
        <%= form.text_field :email, id: :user_email, class: "form-control", placeholder: "E-mail" %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= form.label :password %>
      </div>
      <div class="col-sm-8">
        <%= form.text_field :password, id: :user_password, class: "form-control",type: "password", placeholder: "Password" %>
      </div>
    </div>
    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit "Sign Up!", class: "btn btn-primary btn-lg" %>
      </div>
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to 'Cancel request and return to users listing', users_path %> ]
    </div>
    
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center"> Edit your account </h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align = "center">All Beer Bloggers</h1>
<div align = "center">
<%= will_paginate %>
	<% @users.each do |user| %>
	<ul class="listing">
		<div class="row">
			<div class="well col-md-4 col-md-offset-4">
				<li><%= link_to avatar_for(user), user_path(user) %></li>
				<li class="beer-title">
					<%=	link_to user.username, user_path(user) %>
				</li>
				<li><small><%= pluralize(user.beers.count, "beers") if user.beers %></small>
				</li>
			</div>
		</div>
	</ul>
	<% end %>
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center"> Sign up to BeerBlog! </h1>
<h1>Your localization : <%= localization(@ip) %></h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class = "row">
<div class = "col-md-4 col-md-offset-4 center">
<%= avatar_for @user %>
</div>
</div>
<h4 align="center"><%= @user.username %>s' beers</h4>
<%= render 'beers/beer', obj: @user.beers %>

app/views/welcome/home.html.erb
<div class="jumbotron center">
  <h1>Welcome on Beer Blog!</h1>
  <p>Create Your own Beers database!</p>
  <!--<p><a class="btn btn-primary btn-lg btn-xlarge" href="#" role="button">Sign up!</a></p> -->
  <p><%= link_to 'Sign up!', signup_path, class: "btn btn-primary btn-lg btn-xlarge", "role" => "button" %></p>
</div>